@startuml admin_db
title notify
skinparam componentStyle uml2
hide circles

user : id : UUID(4)
user : timezone : INTEGER
user : email_permission : BOOLEAN
user : browser_permission : BOOLEAN
user : push_permission : BOOLEAN
user : mobile_permission : BOOLEAN

groop : id : UUID(4)
groop : name : TEXT
groop : description : TEXT

user_groop : id : UUID(4)
user_groop : user_id : "FK"
user_groop : groop_id : "FK"

user <-right- user_groop
groop <-left- user_groop

@enduml