# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_sender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_sender.proto\x12\rmessagesender\"f\n\x0e\x42illingMessage\x12\x14\n\x0ctemplate_num\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x18\n\x10role_description\x18\x03 \x01(\t\x12\x13\n\x0b\x65nd_payment\x18\x04 \x01(\t\"%\n\x0fOperationResult\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x32\x66\n\rMessageSender\x12U\n\x12SendBillingMessage\x12\x1d.messagesender.BillingMessage\x1a\x1e.messagesender.OperationResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_sender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BILLINGMESSAGE._serialized_start=39
  _BILLINGMESSAGE._serialized_end=141
  _OPERATIONRESULT._serialized_start=143
  _OPERATIONRESULT._serialized_end=180
  _MESSAGESENDER._serialized_start=182
  _MESSAGESENDER._serialized_end=284
# @@protoc_insertion_point(module_scope)
