# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_service import message_sender_pb2 as message__sender__pb2


class MessageSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBillingMessage = channel.unary_unary(
                '/messagesender.MessageSender/SendBillingMessage',
                request_serializer=message__sender__pb2.BillingMessage.SerializeToString,
                response_deserializer=message__sender__pb2.OperationResult.FromString,
                )


class MessageSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBillingMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBillingMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBillingMessage,
                    request_deserializer=message__sender__pb2.BillingMessage.FromString,
                    response_serializer=message__sender__pb2.OperationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messagesender.MessageSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBillingMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messagesender.MessageSender/SendBillingMessage',
            message__sender__pb2.BillingMessage.SerializeToString,
            message__sender__pb2.OperationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
