# Generated by Django 4.1.5 on 2023-01-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groop',
            options={'verbose_name': 'groop', 'verbose_name_plural': 'groops'},
        ),
        migrations.AlterModelOptions(
            name='groopperiodictask',
            options={'verbose_name': 'groop_periodic_task', 'verbose_name_plural': 'groop_periodic_tasks'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
