# Generated by Django 4.1.5 on 2023-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_template_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file_path',
            field=models.FileField(upload_to='template/', verbose_name='file'),
        ),
    ]
