name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml types-requests mypy flake8 wemake-python-styleguide flake8-html
        pip install -r notify-api/requirements.txt

    - name: Create report directories
      run: |
        mkdir -p reports/mypy_reports/notify-api
        mkdir -p reports/mypy_reports/admin-notify
        mkdir -p reports/styleguide_reports/notify-api
        mkdir -p reports/styleguide_reports/admin-notify

    - name: Run mypy
      run: |
        MYPYPATH=notify-api/src mypy notify-api --ignore-missing-imports --explicit-package-bases --html-report reports/mypy_reports/notify-api
        mypy admin-notify --ignore-missing-imports --html-report reports/mypy_reports/admin-notify

    - name: Run flake8/styleguide
      run: |
        flake8 notify-api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/notify-api
        flake8 admin-notify --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/admin-notify
        
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/
